version: '3'

services:
  db:
    image: 'postgres:latest'
    container_name: ark-mission-tracker-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: amt
      POSTGRES_DB: amt
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  app:
    build: .
    ports:
      - 3001:3000
    container_name: ark-mission-tracker-app
    env_file:
      - .env
    depends_on:
      - db

networks:
  default:
    external:
      name: aqua
