version: '3'

services:
  db:
    image: 'postgres:15'
    container_name: ark-mission-tracker-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: amt
      POSTGRES_DB: amt
    volumes:
      - ./db-data/:/var/lib/postgresql/data/